# ~/.config/bash/aliases.sh

# Sorted in alphabetical order to prevent accidental overriding.
alias ff="fastfetch"
alias ga="git add"
alias gaa="git add ."
alias gb="git branch"
alias gbrn="git branch -m"
alias gbd="git branch -d"
alias gca="git add . && git commit -m"
alias gcm="git commit -m"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcom="git checkout main"
alias grh="git reset --hard"
alias gri="git rebase -i"
alias gri3="git rebase -i HEAD~3"
alias gri5="git rebase -i HEAD~5"
alias gri10="git rebase -i HEAD~10"
alias grs="git reset --soft"
alias grep="grep --color=auto"
alias gs="git status"
alias ls="ls --color=auto"
alias vi="nvim"
alias vim="nvim"
