# ~/.config/kitty/kitty.conf

# Fonts
font_family      family="NotoSansM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Windows
window_padding_width 4 6

# Change cursor shape to block (must override shell)
shell_integration   no-cursor
cursor_shape        block

# Read from/write to clipboard without asking for permission
clipboard_control write-clipboard write-primary read-clipboard read-primary

# Close terminal without asking for permission when apps are open
confirm_os_window_close 0

# Load theme
include current-theme.conf

